import {Platform, StyleSheet} from 'react-native';
import AppConfig from '../../utils/Config';
import {Colors} from '../../utils/colors';
import {windowHeight, windowWidth} from '../../utils/dimensions';

const config = AppConfig();
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: config.primaryColor,
  },
  contentContainer: {
    flex: 1,
    padding: 12,
  },
  buttonText: {
    color: Colors.primaryColors.white,
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 19,
  },
  button: {
    backgroundColor: Colors.primaryColors.pink,
    borderColor: Colors.primaryColors.pink,
    paddingVertical: 9,
    paddingHorizontal: 16,
    borderRadius: 10,
    marginLeft: 10,
  },
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  header: {
    width: windowWidth / 1.35,
  },
  durationText: {
    fontSize: 12,
    fontWeight: '400',
    color: Colors.primaryColors.secondaryGrey,
    lineHeight: 16,
  },
  time: {
    fontSize: 12,
    fontWeight: '600',
    color: Colors.primaryColors.black,
    lineHeight: 16,
  },
  durationView: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: '7.5%',
  },
  videoView: {
    marginTop: 25,
    width: windowWidth / 1.07,
    paddingHorizontal: 2,
  },
  swiperView: {
    flex: 1,
  },
  paginationItem: {width: 8, height: 8, marginHorizontal: 4},
  propsContainer: {
    backgroundColor: config.secondaryColor,
    padding: 15,
    borderRadius: 12,
  },
  propHeading: {
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 22,
    color: Colors.primaryColors.grey,
  },
  id: {
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 22,
    color: Colors.monochromeColors.grey2,
  },
  pagination: {position: 'absolute', top: 0},
  reps: {
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 22,
    color: Colors.monochromeColors.black,
  },
  addSetText: {
    textAlign: 'center',
    paddingTop: 8,
    color: Colors.primaryColors.pink,
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 22,
  },
  dotsHorizontal: {marginHorizontal: '12%'},
  propsTextContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  propsInnerView: {
    backgroundColor: Colors.primaryColors.grey400,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 8,
    marginVertical: 3,
  },
  propsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    marginBottom: 5,
  },
  divider: {
    borderWidth: 0.7,
    borderColor: Colors.primaryColors.paleGrey,
    marginTop: 15,
    marginBottom: 15,
  },
  cancelText: {
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 24,
    textAlign: 'center',
    color: Colors.primaryColors.pink,
  },
  stopWatchText: {
    fontSize: 13,
    fontWeight: '500',
    textAlign: 'center',
    color: Colors.primaryColors.black,
    padding: 6,
  },
  bottomSheetText: {
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 24,
    textAlign: 'center',
    color: Colors.primaryColors.black,
  },
  addModalText: {
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 18,
    marginLeft: 11,
    color: Colors.primaryColors.grey,
    marginBottom: 2,
  },
  cancelButton: {
    backgroundColor: Colors.primaryColors.white,
    marginTop: 10,
    paddingVertical: 12,
    borderRadius: 8,
  },
  stopWatchButton: {
    borderRadius: 7,
    width: '49%',
    margin: 2,
  },
  timerButton: {
    borderRadius: 7,
    width: '49%',
    margin: 2,
    backgroundColor: Colors.primaryColors.white,
  },
  stopWatchContainer: {
    flexDirection: 'row',
    borderRadius: 8,
    backgroundColor: Colors.primaryColors.grey300,
    justifyContent: 'space-between',
  },
  sheetContentContainer: {
    backgroundColor: Colors.primaryColors.white,
    paddingVertical: 12,
    borderRadius: 8,
  },
  sheetContainer: {padding: 16, flex: 1},
  modalContainer: {
    backgroundColor: Colors.primaryColors.white,
    borderRadius: 12,
    paddingVertical: 25,
    paddingHorizontal: 11,
  },
  completedText: {
    fontSize: 24,
    fontWeight: '700',
    lineHeight: 30,
    color: Colors.primaryColors.black,
    marginTop: 20,
    marginBottom: 8,
  },
  description: {
    color: Colors.primaryColors.grey,
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 20,
    marginBottom: 30,
    textAlign: 'center',
  },
  cancel: {
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 22,
    color: Colors.primaryColors.black,
    paddingTop: 8,
    paddingHorizontal: 10,
    textAlign: 'center',
  },
  modalButton: {
    width: windowWidth / 1.3,
    paddingVertical: 6,
    backgroundColor: Colors.primaryColors.pink,
    borderColor: Colors.primaryColors.pink,
    alignSelf: 'center',
  },
  modalButtonText: {
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 24,
    color: Colors.primaryColors.white,
  },
  messagesContainer: {
    flex: 1,
    backgroundColor: Colors.primaryColors.lightGrey,
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  topBar: {
    backgroundColor: Colors.primaryColors.white,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 12,
  },
  comments: {
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 24,
    color: Colors.primaryColors.black,
  },
  extra: {width: 25},
  messageImage: {alignSelf: 'center'},
  bottomTab: {
    backgroundColor: Colors.primaryColors.white,
    paddingHorizontal: 15,
    paddingTop: 10,
    paddingBottom: 30,
  },
  bottomContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  image: {width: 45, height: 45},
  inputView: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: 20,
    borderColor: Colors.primaryColors.paleGrey,
    paddingHorizontal: 14,
    paddingVertical: Platform.OS === 'ios' ? 10 : 0,
  },
  input: {
    width: windowWidth / 2.5,
    fontSize: 14,
    fontWeight: '500',
    color: Colors.primaryColors.secondaryGrey,
  },
  smiley: {width: 30},
  sendButton: {
    height: 40,
    width: 40,
    borderRadius: 30,
    backgroundColor: Colors.primaryColors.pink,
    alignItems: 'center',
    justifyContent: 'center',
  },
  delivered: {
    alignSelf: 'flex-end',
    color: Colors.primaryColors.secondaryGrey,
    marginBottom: 3,
  },
  message: {
    color: Colors.primaryColors.white,
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 22,
  },
  messagesView: {
    backgroundColor: Colors.primaryColors.black,
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginVertical: 3,
    alignSelf: 'flex-end',
    borderRadius: 15,
    marginLeft: 10,
  },
  messagesArray: {
    flex: 1,
    overflow: 'hidden',
  },
  flatList: {
    flex: 1,
    right: 10,
  },
  videoContainer: {
    flex: 1,
  },
  commentsImage: {
    width: windowWidth / 2,
    height: windowHeight / 4,
    resizeMode: 'cover',
    borderRadius: 19,
    alignSelf: 'flex-end',
    marginVertical: 8,
  },
  modalInput: {
    padding: 10,
    marginHorizontal: 10,
    borderColor: Colors.primaryColors.secondaryGrey,
    borderWidth: 1,
    borderRadius: 8,
    marginBottom: 8,
    color: Colors.primaryColors.black,
  },
  circle: {
    width: 20,
    height: 20,
    borderWidth: 1,
    borderRadius: 15,
    borderColor: Colors.primaryColors.secondaryGrey,
  },
  error: {
    color: Colors.primaryColors.pink,
    marginLeft: '4%',
    marginTop: -8,
  },
  flatListContent: {
    flexGrow: 1,
    flexDirection: 'column-reverse',
  },
});
