export default {
  onboarding_screen: 'Onboarding Screen',
  onboarding_note: 'Welcome to onboarding Screen',
  login_screen: 'Login Screen',
  signup_screen: 'Signup Screen',
  foget_screen: 'Forget Password Screen',
  login_btn_text: 'Log in',
  get_started_btn_txt: 'Get Started',
  name_place_holder: 'Enter name',
  email_place_holder: 'Enter email',
  password_place_holder: 'Please enter your password',
  login_note: 'Log in to Stridist',
  theme_screen: 'Theme Screen',
  go_back_btn: 'GO BACK',
  env: 'Environment',
  dashboard_screen: 'Dashboard Screen',
  workout_screen: 'Workout Screen',
  add_cart: 'Add to cart',
  empty_cart: 'Cart is Empty',
  sample_screen: 'Sample Screen',
  remove_item: 'Remove Item',
  no_data: 'No data found',
  menu_screen: 'Menu Screen',
  menu: 'Menu',
  groups: 'Groups',
  activity: 'Activity',
  settings: 'Settings',
  rateReview: 'Rate & Review',
  help: 'Help',
  signout: 'Sign out',
  profile_screen: 'Profile Screen',
  stepTracker_screen: 'Step Tracker Screen',
  nutrition_screen: 'Nutrition Screen',
  weight_screen: 'Weight Screen',
  goals_screen: 'Goals Screen',
  profile_workout_hitory: 'Profile Workout History',
  progress_photos_screen: 'Progress Photos Screen',
  exercise_history_screen: 'Exercise History Screen',
  metrics_weight_screen: 'Metrics Weight Screen',
  add_weight_screen: 'Add Weight Screen',
  add_body_fat_screen: 'Add Body Fat Screen',
  home_screen: 'Home Screen',
  profile: 'Profile',
  height: 'Height',
  weight: 'Weight',
  metrics: 'Metrics',
  weight_graph: 'Weight_Graph',
  age: 'Age',
  userName: 'Saif Uddin',
  city: 'New York, NY',
  email: 'sample@stridist.com',
  active: 'Active',
  userAge: '27',
  weightlbs: '124lbs',
  userHeight: '5' + "'" + '8' + '"',
  viewText: 'View',
  View: 'View ',
  show: 'Show ',
  addnew: 'Add new check-in',
  measurements: 'Measurements',
  transparent: "'transparent'",
  hide: 'Hide ',
  goals: 'Goals',
  setgoals: 'Set Goal',
  add: 'Add',
  progressPhotos: 'Progress Photos',
  addphoto: 'Add Photo',
  date04: '04/04',
  date05: '04/05',
  date06: '04/06',
  exercise: 'Exercises',
  exercisetext: 'Exercise',
  steps: 'Steps',
  nutrition: 'Nutrition',
  days: 'Days',
  daily: 'Daily',
  week: 'Weeks',
  weekly: 'Weekly',
  month: 'Months',
  monthly: 'Monthly',
  yearly: 'Yearly',
  year: 'Year',
  training: 'Training Days',
  offdays: 'Off Days',
  macroTarget: 'Macro Targets',
  startdate: 'Start date',
  dateApr: 'Apr 18,2022',
  dateMay: 'May 5,2022',
  comments: 'Comments',
  calories: 'Calories only',
  workouts: 'Workouts',
  titleHomeScreen: 'Hi, ',
  descriptionHomeScreen: "Don't Let anyone work header than you",
  thisWeek: 'This week,',
  startWorkout: 'Start Workout',
  todayHave: 'Today you have',
  details: 'Details',
  workout: 'Workouts',
  three: '3',
  cardio: 'Cardio',
  squat: 'Squat',
  running: 'Running',
  weightlift: 'Weight Lift',
  todayProgress: 'Today Progress',
  habits: 'Habits',
  lesson: 'Lesson',
  programs_Screen: 'Programs Screen',
  message_screen: 'Message Screen',
  addnew_screen: 'AddNew Screen',
  bottomtab: 'Bottom Tab',
  home: 'Home',
  program: 'Program',
  message: 'Message',
  percentage40: '40%',
  percentage10: '10%',
  stackChartSuffix: ' m',
  null: '',
  buttonOpacity: 0.8,
  takePhoto: 'Take a Photo',
  chooseGallery: 'Choose from Gallery',
  permissiontitle: 'Stridist App Camera Permission',
  permissionmessage: 'Stridist needs access to your camera',
  cancel: 'Cancel',
  ok: 'OK',
  images: 'images',
  ios: 'ios',
  profileheader: 'Profile_Header',
  back: 'Back',
  resizemode: 'contain',
  chartValue: '170.8',
  marDate: 'Mar 26',
  playVideo: 'PLAY VIDEO',
  completed: 'Completed',
  missed: 'Missed',
  upcoming: 'Upcoming',
  workoutRearrange_screen: 'Workout Rearrange',
  rearrange: 'Rearrange',
  workoutHistory_screen: 'Workout History',
  history: 'History',
  bestset: 'Best Set',
  workoutExcercise_screen: 'Workout Excercise',
  exercisedetail_screen: 'Exercise Detail',
  addexercise: 'Add Exercises',
  resetexercise: 'Reset Exercises',
  exercise4: 'Exercises',
  time: 'Time',
  done: 'Done',
  workoutHistoryDetail_screen: 'Workout History Details',
  workoutHistoryCalender_screen: 'Workout History Calender',
  completeWorkout: 'Completed Workout',
  workoutDescription: 'What would you like to do?',
  workoutResult: 'Edit Workout Result',
  rm: '1RM',
  squatBarbell: 'Squat (Barbell)',
  workoutdetails: 'Workout details',
  time030: '0:30',
  time7to730: '7:00 am to 7:30 am',
  howWorkout: 'How was the workout',
  difficult: 'Difficult 🔥',
  trainingmin: 'Training min',
  resttimer: 'Rest Timer',
  timeractivated: 'Rest Timer is activated',
  timerdeactivated: 'Rest Timer is deactivated',
  autoplayvideo: 'Autoplay Videos',
  autoplayon: 'Autoplay is on',
  autoplayoff: 'Autoplay is off. Tap to play videos',
  downloadworkout: 'Download Workout',
  printworkout: 'Print Workout',
  finish: 'Finish',
  duration: 'Duration: ',
  time530: '05:34',
  addset: 'Add set',
  deletelast: 'Delete last set',
  addSet: 'Add Set',
  set: 'Set',
  reps: 'Reps',
  weightlb: 'Weight(lb)',
  allexercises: 'All exercises will be completed',
  changesnotsave:
    'Changes have not been saved yet.Would you like to save before exiting the workout?',
  finishWorkout: 'Finish Workout',
  savechanges: 'Save Your Changes?',
  commentsdot: 'Comment...',
  delivered: 'Delivered',
  stopWatch: 'StopWatch',
  timer: 'Timer',
  reset: 'Reset',
  dumbbellRearDeltScreen: 'DumbbellRearDeltScreen',
  exerciseDetailsCongratulations: 'Exercise Details Congratulations',
  about: 'About',
  add_your_own_note: 'Add your own note',
  dumbbell_Rear_Delt_Row: 'Dumbbell Rear Delt Row',
  historDetails1: `This exercise is best performed inside a squat rack for safety purposes. To begin, first set the bar on a rack just above shoulder level. Once the correct height is chosen and the bar is loaded, step under the bar and place the back of your shoulders (slightly below the neck) across it.\n\nHold on to the bar using both arms at each side and lift it off the rack by first pushing with your legs and at the same time straightening your torso.\n\nStep away from the rack and position your legs using a shoulder-width medium stance with the toes slightly pointed out keep your head up at all times and maintain a straight back. This will be your
starting position.`,
  instructions: 'Instructions',
  endofWorkout: 'End of workout survey',
  howdidfeel: 'How did you feel?',
  trainingtime: 'Training Time',
  notes: 'Notes',
  notesplaceholder: 'ex. Need to buy a bandage for the bench press',
  confirm: 'Confirm',
  m1: '1M',
  m2: '2M',
  y1: '1Y',
  april08: 'April 8',
  congratulations: 'Congratulations!',
  completedWorkout: 'You completed your 120th workout',
  recordedDate: 'Recorded Apr 05.23',
  beforeTraining: 'Well-being before training',
  afterTraining: 'Well-being after training',
  mind: 'Mind',
  hyped5: '5 Hyped',
  body: 'Body',
  strong5: '5 Strong',
  feel: 'Feels',
  hard4: '4 Hard',
  sixty: '60',
  exerciseDetailsShareScreen: 'Exercise Details Share',
  secondWorkout: 'This is your 2nd workout',
  goodJob: 'Good Job',
  shareWorkout: 'Share workout - Tag @stridist',
  start: 'Start',
  stop: 'Stop',
  shareMessage: 'Dumbbell Rear Delt Row \nThis is your 2nd Workout',
  min: 'MIN',
  sec: 'SEC',
  hr: 'HR',
  empty: '',
  dash: ' - ',
  zero: '0',
  videotitle: 'Video title',
  goalname: 'Goal name',
  squats: 'Squats',
  pleaseaddset: 'Please add set',
  pleaseaddreps: 'Please add reps',
  pleaseaddweight: 'Please add weight(lb)',
  pleaseaddtitle: 'Please add video title',
  pleaseselectvideo: 'Please select a video',
  steptracker: 'Step Tracker',
  logallmetrics: 'Log all Metrics',
  today: 'TODAY',
  stepsummary: 'Step Summary',
  settarget: 'Set Target',
  average: 'Average',
  steps70: '7,004 steps',
  steps35k: '35,000 steps',
  steps100k: '1,25,000 steps',
  steps1m: '1.3 million steps',
  distance: 'Distance',
  km5: '5.7 km',
  nutritionSummary: 'Nutrition Summary',
  youconsumed: 'You have consumed',
  macro: 'MACRO',
  consumed: 'CONSUMED',
  remaining: 'REMAINING',
  goal: 'GOAL',
  actual: 'ACTUAL',
  macroDistribution: 'Macro Distribution',
  weightSummary: 'Weight Summary',
  goalWeight: 'GOAL WEIGHT',
  weightweek: '170.7',
  weekago: '1 WEEK AGO',
  complete: 'COMPLETE',
  datemarch: '26 MARCH 2023',
  five7: '5.7',
  togo: 'TO GO',
  weightchart: 'Weight Chart',
  weightList: 'Weight List',
  goals4: '4 Goals',
  workouthistory: 'Workout History',
  workoutshistory: 'Workouts History',
  exercisehistory: 'Exercises History',
  setPerformed: 'Sets Performed',
  rm1: '1 RM',
  addweight: 'Add Weight',
  date: 'Date',
  vslyash: '| ',
  selectunit: 'Select Unit',
  lb: 'lb',
  kg: 'kg',
  g: 'g',
  bodyfat: 'Body Fat',
  percentage: '%',
  addbodyfat: 'Add Body Fat',
  time7: '7:00 am',
  saveworkout: 'Save Workout',
  exitwithout: 'Exit Without Saving',
  km25: '25 km',
  km110: '110 km',
  km1200: '1250 km',
  progress: 'Progress',
  logingoogle: 'Sign in with Google',
  loginfb: 'Sign in with Facebook',
  loginapple: 'Sign in with Apple',

  forgetpassword: 'Forget Password?',
  haveanaccount: `Don't have an account? `,
  ascoach: 'Sign Up as Coach',
  forget_password_note: 'Forgot your password?',
  forget_pass_btn_text: 'Send reset link',
  back_to_login: 'Back to Login',
  signup_heading_text: 'Get Started TODAY',
  alreadyaccount: 'Already have an account? ',
  aslogin: 'Log In',
  freeTrail: 'Start you 14 day free trail below',
  sign_up_btn_text: 'Sign Up',
  signup_terms_text: 'By signing up, you agree to our ',
  signup_terms_text1: 'terms of services ',
  signup_terms_text2: 'and ',
  signup_terms_text3: 'privacy policy',
  duplicate: 'Duplicate',
  archive: 'Archive',
  setFolder: 'Set Folder',
  group_screen: 'Group Screen',
  group: 'Groups',
};
