import {StyleSheet} from 'react-native';
import {Colors} from '../../utils/colors';

export const styles = StyleSheet.create({
  sectionList: {
    flex: 1,
    backgroundColor: Colors.primaryColors.lightGrey,
    marginTop: '3%',
    borderRadius: 12,
  },
  title: {paddingVertical: 5, color: Colors.primaryColors.secondaryGrey},
  renderItem: {paddingVertical: 4},
  container: {flex: 1, marginTop: '5%'},
  calenderStrip: {
    height: 80,
    paddingTop: 10,
    paddingBottom: 10,
    borderRadius: 12,
  },
  dateNumStyle: {
    color: Colors.primaryColors.black,
    marginTop: 8,
    paddingTop: 3,
    borderColor: Colors.primaryColors.paleGrey,
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 22,
    borderWidth: 0.9,
    borderRadius: 15,
    width: 30,
    height: 30,
    alignSelf: 'center',
  },
  iconContainer: {flex: 0.1},
  highlightDateNameStyle: {
    color: Colors.primaryColors.white,
    borderWidth: 1,
    borderColor: Colors.primaryColors.pink,
    height: 25,
    width: 25,
    borderRadius: 13,
    overflow: 'hidden',
    paddingTop: 6,
    marginBottom: 4,
    backgroundColor: Colors.primaryColors.pink,
  },
  highlightDateNumberStyle: {
    color: Colors.primaryColors.pink,
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 22,
    height: 32,
    alignSelf: 'center',
  },
  highlightDateContainer: {
    backgroundColor: Colors.primaryColors.white,
  },
  dateName: {color: Colors.primaryColors.black},
  circle: {
    backgroundColor: Colors.primaryColors.paleGrey,
    height: 13,
    width: 13,
    borderRadius: 15,
    marginRight: 10,
    marginTop: -23,
  },
  dashedLine: {
    position: 'absolute',
    top: -9,
    left: 6,
    height: 115,
    borderWidth: 0.5,
    borderColor: Colors.primaryColors.lightestPurple,
    borderStyle: 'dashed',
  },
});
